Ensure all matrices are converted to CsparseMatrix format
preventing this error:
```
Error in py_call_impl(callable, call_args$unnamed, call_args$named) :
  AttributeError: 'PyCapsule' object has no attribute 'shape'
Run `reticulate::py_last_error()` for details.
Calls: <Anonymous> ... do.call -> <Anonymous> -> <Anonymous> -> py_call_impl
Execution halted
```